package builtin

import "ccLoad/internal/protocol"

// Register installs the built-in protocol translators used by the proxy.
func Register(reg *protocol.Registry) {
	reg.RegisterRequest(protocol.OpenAI, protocol.Gemini, cliproxyOpenAIRequestToGemini)
	reg.RegisterRequest(protocol.Gemini, protocol.OpenAI, cliproxyGeminiRequestToOpenAI)
	reg.RegisterStreamResponse(protocol.Gemini, protocol.OpenAI, cliproxyGeminiResponseToOpenAIStream)
	reg.RegisterStreamResponse(protocol.OpenAI, protocol.Gemini, cliproxyOpenAIResponseToGeminiStream)
	reg.RegisterNonStreamResponse(protocol.Gemini, protocol.OpenAI, cliproxyGeminiResponseToOpenAINonStream)
	reg.RegisterNonStreamResponse(protocol.OpenAI, protocol.Gemini, cliproxyOpenAIResponseToGeminiNonStream)
	reg.RegisterRequest(protocol.OpenAI, protocol.Anthropic, cliproxyOpenAIRequestToAnthropic)
	reg.RegisterStreamResponse(protocol.Anthropic, protocol.OpenAI, cliproxyAnthropicResponseToOpenAIStream)
	reg.RegisterNonStreamResponse(protocol.Anthropic, protocol.OpenAI, cliproxyAnthropicResponseToOpenAINonStream)
	reg.RegisterRequest(protocol.Anthropic, protocol.OpenAI, cliproxyAnthropicRequestToOpenAI)
	reg.RegisterStreamResponse(protocol.OpenAI, protocol.Anthropic, cliproxyOpenAIResponseToAnthropicStream)
	reg.RegisterNonStreamResponse(protocol.OpenAI, protocol.Anthropic, cliproxyOpenAIResponseToAnthropicNonStream)
	reg.RegisterRequest(protocol.OpenAI, protocol.Codex, cliproxyOpenAIRequestToCodex)
	reg.RegisterStreamResponse(protocol.Codex, protocol.OpenAI, cliproxyCodexResponseToOpenAIStream)
	reg.RegisterNonStreamResponse(protocol.Codex, protocol.OpenAI, cliproxyCodexResponseToOpenAINonStream)
	reg.RegisterRequest(protocol.Anthropic, protocol.Gemini, cliproxyAnthropicRequestToGemini)
	reg.RegisterStreamResponse(protocol.Gemini, protocol.Anthropic, cliproxyGeminiResponseToAnthropicStream)
	reg.RegisterNonStreamResponse(protocol.Gemini, protocol.Anthropic, cliproxyGeminiResponseToAnthropicNonStream)
	reg.RegisterRequest(protocol.Gemini, protocol.Anthropic, cliproxyGeminiRequestToAnthropic)
	reg.RegisterStreamResponse(protocol.Anthropic, protocol.Gemini, cliproxyAnthropicResponseToGeminiStream)
	reg.RegisterNonStreamResponse(protocol.Anthropic, protocol.Gemini, cliproxyAnthropicResponseToGeminiNonStream)
	reg.RegisterRequest(protocol.Codex, protocol.Gemini, cliproxyCodexRequestToGemini)
	reg.RegisterStreamResponse(protocol.Gemini, protocol.Codex, cliproxyGeminiResponseToCodexStream)
	reg.RegisterNonStreamResponse(protocol.Gemini, protocol.Codex, cliproxyGeminiResponseToCodexNonStream)
	reg.RegisterRequest(protocol.Gemini, protocol.Codex, cliproxyGeminiRequestToCodex)
	reg.RegisterStreamResponse(protocol.Codex, protocol.Gemini, cliproxyCodexResponseToGeminiStream)
	reg.RegisterNonStreamResponse(protocol.Codex, protocol.Gemini, cliproxyCodexResponseToGeminiNonStream)
	reg.RegisterRequest(protocol.Codex, protocol.Anthropic, cliproxyCodexRequestToAnthropic)
	reg.RegisterStreamResponse(protocol.Anthropic, protocol.Codex, cliproxyAnthropicResponseToCodexStream)
	reg.RegisterNonStreamResponse(protocol.Anthropic, protocol.Codex, cliproxyAnthropicResponseToCodexNonStream)
	reg.RegisterRequest(protocol.Anthropic, protocol.Codex, cliproxyAnthropicRequestToCodex)
	reg.RegisterStreamResponse(protocol.Codex, protocol.Anthropic, cliproxyCodexResponseToAnthropicStream)
	reg.RegisterNonStreamResponse(protocol.Codex, protocol.Anthropic, cliproxyCodexResponseToAnthropicNonStream)
	reg.RegisterRequest(protocol.Codex, protocol.OpenAI, cliproxyCodexRequestToOpenAI)
	reg.RegisterStreamResponse(protocol.OpenAI, protocol.Codex, cliproxyOpenAIResponseToCodexStream)
	reg.RegisterNonStreamResponse(protocol.OpenAI, protocol.Codex, cliproxyOpenAIResponseToCodexNonStream)
}
